deploy production:
  stage: deploy
  image: pstauffer/curl
  script:
    - RESP=$(curl -X POST ${PROD_SERVICE_HOOK_APP})
    - if echo $RESP | grep -q ‘err’; then exit 1; fi
    - RESP=$(curl -X POST ${PROD_SERVICE_HOOK_NGINX})
    - if echo $RESP | grep -q ‘err’; then exit 1; fi
  only:
    - master
  environment:
    name: production
    url: https://admin.desiretec.com
  variables:
    GIT_STRATEGY: none
  when: manual

deploy pre production:
  stage: deploy-pre-production
  image: pstauffer/curl
  script:
    - RESP=$(curl -X POST ${PRE_PROD_SERVICE_HOOK_APP})
    - if echo $RESP | grep -q ‘err’; then exit 1; fi
    - RESP=$(curl -X POST ${PRE_PROD_SERVICE_HOOK_NGINX})
    - if echo $RESP | grep -q ‘err’; then exit 1; fi
  only:
    - master
  environment:
    name: pre-production
    url: https://admin-stage.desiretec.com
  variables:
    GIT_STRATEGY: none

