# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --update py-pip
  - pip install docker-compose

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-stage:
  stage: build
  script:
#    - mkdir $DOCKER_CERT_PATH
#    - echo "$DOCKER_MACHINE_CA" > $DOCKER_CERT_PATH/ca.pem
#    - echo "$CLIENT_DOCKER_CERT" > $DOCKER_CERT_PATH/cert.pem
#    - echo "$CLIENT_DOCKER_CERT_KEY" > $DOCKER_CERT_PATH/key.pem
    - docker-compose build
    - docker-compose down
    - docker-compose up -d --force-recreate
#    - rm -rf $DOCKER_CERT_PATH
  only:
    - development
  variables:
    DOCKER_HOST: "tcp://docker:2376"
