deploy::Production:
  stage: deploy
  image: pstauffer/curl
  script:
    - RESP=$(curl -X POST ${PROD_SERVICE_HOOK_APP})
    - if echo $RESP | grep -q ‘err’; then exit 1; fi
    - RESP=$(curl -X POST ${PROD_SERVICE_HOOK_NGINX})
    - if echo $RESP | grep -q ‘err’; then exit 1; fi
  only:
    - master
  variables:
    SERVICE_WEBHOOK: ${PROD_SERVICE_HOOK_APP}
    ECHO_SERVICE_WEBHOOK: ${PROD_SERVICE_HOOK_NGINX}

