version: '3'

volumes:
  mariadb_data:
    driver: local

networks:
    nginx-proxy-wildcard:
      external:
        name: nginx-proxy-wildcard

services:
  app:
    image: desiretecmvp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis
    volumes:
      - "./storage:/var/www/html/storage"
    networks:
      nginx-proxy-wildcard:
        ipv4_address: 178.30.0.4

  mariadb:
    image: mariadb:latest
    volumes:
      - "mariadb_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
  redis:
    image: redis:latest
