version: "3"

services:
  app:
    image: git.desiretec.com:5005/desiretec/desiretec-mvp-laravel/master:latest
    depends_on:
      - redis
      - laravel-echo-server
    volumes:
      - "app_storage:/var/www/html/storage"
    environment:
      - APP_NAME="desiretec pre prod MVP"
      - APP_ENV=production
      - APP_KEY=${APP_KEY_PROD}
      - APP_DEBUG=false
      - APP_LOG=daily
      - LOG_CHANNEL=daily
      - APP_URL=https://mvp.preprod.desiretec.com
      - TIMEZONE=Europe/Berlin
      - APP_JS_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=${RDS_HOST}
      - DB_PORT=3306
      - DB_DATABASE=default
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PW}
      - ENABLE_REGISTRATION=true
      - REQUIRES_APPROVAL=false
      - BROADCAST_DRIVER=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_DRIVER=ses
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=mvpdesiretec@gmail.com
      - MAIL_PASSWORD=${MAIL_PW}
      - MAIL_ENCRYPTION=ssl
      - JWT_SECRET=${JWT_SECRET_PROD}
      - JWT_TTL=44640
      - JWT_REFRESH_TTL=null
      - AWS_KEY=AKIAJ7MNWL257JAF3UWQ
      - AWS_SECRET=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
      - AWS_REGION=eu-central-1
      - AWS_BUCKET=desiretec
    networks:
      - traefik
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`mvpprod.desiretec.com`,`trendtours.reisewunschservice.de`,`novasol.reisewunschservice.de`,`*.reisewunschservice.de`,`*.wish-service.com`,`*.reise-wunsch.de`,`*.reise-wunsch.com`,`kreuzfahrtberatung.reisewunschservice.de`)
        #        - traefik.frontend.whiteList.sourceRange=18.195.236.85/32
        - traefik.docker.network=traefik
        - traefik.http.services.portainer.loadbalancer.server.port=80
        - traefik.http.routers.portainer.tls.certresolver=le1
        - traefik.http.routers.portainer.entrypoints=websecure
  redis:
    image: redis:latest
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  laravel-echo-server:
    build:
      context: ./laravel-echo-server
    depends_on:
      - redis
    volumes:
      - "laravel_echo_storage:/app/storage_json:ro"
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


volumes:
  app_storage:
    driver: local
  laravel_echo_storage:
    driver: local

networks:
  traefik:
    external: true
  backend:
