version: '3'
services:
    app:
      ports:
        - "80"
      volumes:
        - /var/www/desiretec-mvp-stage/storage:/var/www/html/storage
      environment:
        - VIRTUAL_HOST=mvp.desiretec.com
        - LETSENCRYPT_HOST=mvp.desiretec.com
        - LETSENCRYPT_EMAIL=info@desiretec.com
