version: '3'

volumes:
  mariadb_data:
    driver: local

services:
  app:
    image: desiretecmvp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis
    volumes:
      - "./storage:/var/www/html/storage"
  mariadb:
    image: mariadb:latest
    volumes:
      - "mariadb_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
  redis:
    image: redis:latest
