version: '3'

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - mariadb
        - redis
        - laravel-echo-server
      volumes:
        - /var/www/desiretec-mvp-stage/storage:/var/www/html/storage
      environment:
        - VIRTUAL_HOST=mvp.desiretec.com,novasol.wunsch-service.de,trendtours.reise-wunsch.com,*.wish-service.com,*.reise-wunsch.de,*.reise-wunsch.com
      networks:
        nginx-proxy-wildcard:
          ipv4_address: 178.30.0.3

    mariadb:
      image: mariadb:latest
      environment:
        - MYSQL_USER=default
        - MYSQL_PASSWORD=${DB_STAGE_PW}
        - MYSQL_DATABASE=default
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
#      ports:
#        - "127.0.0.1:3300:3306"
      networks:
        nginx-proxy-wildcard:
          ipv4_address: 178.30.0.4

    redis:
      image: redis:latest
      networks:
        nginx-proxy-wildcard:
          ipv4_address: 178.30.0.5

    laravel-echo-server:
      build:
        context: ./laravel-echo-server
      volumes:
        - /etc/letsencrypt:/app/mvp_certs:ro
#      ports:
#        - 6001:6001
      links:
        - redis
      networks:
        nginx-proxy-wildcard:
          ipv4_address: 178.30.0.6

networks:
    nginx-proxy-wildcard:
      external:
        name: nginx-proxy-wildcard
