<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Teilnahmebedingungen Template
    |--------------------------------------------------------------------------
    |
    | The following template is the default template for Teilnahmebedingungen of every WL
    | this template is given in the following link, please follow it by the link given
    | https://docs.google.com/document/d/1_--D3YYMGQsGZs8g9bME0hgsrTCHjGoM00XUoPIkXbo/edit
    |
    */

    'template'     => '<p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Bedingungen f&uuml;r die Nutzung des </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">-Reisewunschportals</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>1. Funktion des </strong></span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">-Reisewunschportals</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>, Nutzungsbedingungen</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">1.1 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> bietet &uuml;ber das Online-Tool &bdquo;</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">-Reisewunschportal&ldquo; unentgeltlich die technische M&ouml;glichkeit Suchanzeigen nach Reiseangeboten (&bdquo;Reisew&uuml;nsche&ldquo;) aufzugeben und so pers&ouml;nlichen Kontakt zu den </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> Reiseberatern zum Zwecke einer individuellen Angebotskommunikation herzustellen.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">1.2 F&uuml;r die Nutzung des Online-Tools gelten diese Nutzungsbedingungen, die nach Ma&szlig;gabe von Ziffer 8.1 ge&auml;ndert werden k&ouml;nnen.</span></span></span></p>
    &nbsp;

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>2. Anmeldung</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">2.1 Das Online-Tool ist &uuml;ber ein entsprechendes Dialogfeld auf der Webseite des </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> sowie &uuml;ber </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$URL-REISEWUNSCHPORTAL</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> zu erreichen. Die Nutzung des Online-Tools setzt die Anmeldung als Nutzer voraus.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">2.2 Die Anmeldung ist nur vollj&auml;hrigen und unbeschr&auml;nkt haftenden Personen gestattet.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">2.3 Die Anmeldung erfolgt durch Einsendung der E-Mail-Adresse sowie des Reisewunsches und ggf. weiterer Suchkriterien sowie der Akzeptanz der Nutzungsbedingungen. Sie wird durch Zusendung einer Best&auml;tigungsmail mit einem individuellen Zugangslink durch </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> an die angegebene E-Mail-Adresse abgeschlossen.&nbsp;&nbsp;</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">2.4 &Uuml;ber den Zugangslink kann der Nutzer seinen Reisewunsch einschlie&szlig;lich der weiteren angegeben Daten im Online-Tool jederzeit einsehen, anpassen oder deaktivieren. Passt der Nutzer den Reisewunsch an oder deaktiviert ihn, verschickt das Online-Tool eine entsprechende Info-Mail an ihn.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">2.5 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> &uuml;berpr&uuml;ft nicht die Richtigkeit der Nutzerdaten.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">2.6 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> beh&auml;lt sich das Recht vor, nach alleinigem Ermessen und ohne Ank&uuml;ndigung den Zugang von Nutzern zum Online-Tool oder dessen Teilen zu verweigern und/oder den Betrieb des Online-Tools einzustellen.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">&nbsp;</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>3. Reisew&uuml;nsche, Bearbeitung</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">3.1 Ein Reisewunsch stellt nur eine unverbindliche Anfrage und kein rechtlich bindendes Angebot dar.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">3.2 Die in das Online-Tool eingegebenen Reisew&uuml;nsche der Nutzer werden durch das System an </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> Reiseberater zur weiteren Bearbeitung weitergeleitet.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">3.3 Die Reisew&uuml;nsche werden nicht ver&ouml;ffentlicht.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">3.4 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> Reiseberater k&ouml;nnen auf einen Reisewunsch mit einem Angebotsvorschlag reagieren. Dieser Vorschlag ist rechtlich unverbindlich, soweit darin nichts anderes bestimmt ist.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">3.5 Nachdem ein Reiseberater einen Reisewunsch bearbeitet und das Angebot in das Online-Tool eingestellt hat, bekommt der Nutzer eine E-Mail, in der erneut ein Link zum Reisewunsch und dem Angebot enthalten ist.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">3.6 Der Nutzer, welcher den Reisewunsch eingestellt hat, kann auf den Vorschlag hin den </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> Reiseberater kontaktieren. Er ist jedoch nicht verpflichtet, auf einen Vorschlag zu reagieren.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">3.7 Der Nutzer kann w&auml;hlen, &uuml;ber welchen Weg (E-Mail, Telefon) er weiter mit dem Reiseberater kommunizieren m&ouml;chte. Solange der Nutzer keine Kontaktdaten f&uuml;r einen Direktkontakt mitteilt, erfolgt die Kommunikation ausschlie&szlig;lich &uuml;ber das Online-Tool.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">&nbsp;</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>4. Pflichten des Nutzers, Verantwortung f&uuml;r Inhalte</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">4.1 Der Nutzer ist verpflichtet, den pers&ouml;nlichen Zugangslink geheim zu halten.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">4.2 Der Nutzer ist grunds&auml;tzlich f&uuml;r alle &uuml;ber seinen Zugangslink vorgenommenen Aktivit&auml;ten verantwortlich. Die Regelungen dieses Absatzes gelten nicht, wenn der Nutzer einen etwaigen Missbrauch seines Zugangslinks nicht zu vertreten hat, weil keine Sorgfaltspflichtverletzung des Nutzers vorliegt. Der Nutzer ist verpflichtet, </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> umgehend zu informieren, wenn er Anhaltspunkte f&uuml;r einen Missbrauch seines Zugangslink durch Dritte hat.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">4.3 Der Nutzer ist verpflichtet, bei der Einstellung von Reisew&uuml;nschen und sonstigen Inhalten s&auml;mtliche geltende Rechtsvorschriften, Rechte Dritter und diese Nutzungsbedingungen zu beachten. Er ist f&uuml;r die Rechtm&auml;&szlig;igkeit, Richtigkeit und Vollst&auml;ndigkeit aller von ihm eingestellten Inhalte verantwortlich und haftet f&uuml;r die Verletzung von Rechtsvorschriften oder von rechten Dritter durch von ihm eingestellte Inhalte.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">4.4 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> &uuml;berpr&uuml;ft die in das Online-Tool eingestellten Inhalte der Nutzer grunds&auml;tzlich nicht und &uuml;bernimmt keine Haftung. </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span>r <span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">behält sich aber das Recht vor, die Inhalte zu &uuml;berpr&uuml;fen, auch wenn keine&nbsp; Verpflichtung besteht.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">4.5 Der Nutzer erh&auml;lt etwaige Informationen &uuml;ber die von ihm im Online-Tool hinterlegte E-Mail-Adresse. Es obliegt ihm, sicherzustellen, dass er unter dieser E-Mail-Adresse erreichbar ist.</span></span></span><br />
    <br />
    <br />
    <span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>5. Unzul&auml;ssige Nutzungshandlungen, Ma&szlig;nahmen bei Verst&ouml;&szlig;en, Freistellung</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">5.1 Die folgenden Handlungen sind unzul&auml;ssig:&nbsp; Das Einstellen von anderen Inhalten als Reisew&uuml;nschen. Das Einstellen von unzul&auml;ssigen Inhalten; unzul&auml;ssige Inhalte, die gegen die Nutzungsbedingungen oder gegen gesetzliche Verbote oder die guten Sitten versto&szlig;en oder Rechte Dritter verletzen. Die Offenlegung und Weitergabe des Zugangslinks zum Online-Tool. Das automatisierte Auslesen der im Online-Tool befindlichen Daten sowie der Aufbau eigener Suchsysteme, Dienste und Verzeichnisse unter Zuhilfenahme der im Online-Tool abrufbaren Inhalte sowie das vielfache Erstellen gleicher Inhalte. Die Verwendung oder das Aufspielen von Dateien, die Viren, besch&auml;digte Dateien, Software oder sonstige Mechanismen oder Inhalte enthalten, welche das Online-Tool oder dessen Nutzer, deren Rechner, die Server von </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> oder die auf den Rechnern der Nutzer oder von </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> verwendete Software ausspionieren, attackieren oder in sonstiger Weise beeintr&auml;chtigen k&ouml;nnten.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">5.2 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> kann folgende Ma&szlig;nahmen ergreifen, wenn konkrete Anhaltspunkte daf&uuml;r bestehen, dass ein Nutzer gesetzliche Vorschriften, Rechte Dritter oder diese Bedingungen verletzt, oder wenn </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> ein sonstiges berechtigtes Interesse hat: L&ouml;schen von Reisew&uuml;nschen oder sonstigen Inhalten, Verwarnung des Nutzers, Beschr&auml;nkung der Nutzungsm&ouml;glichkeiten des Online-Tools durch den Nutzer, so dass u.a. keine Inhalte mehr eingestellt werden k&ouml;nnen, L&ouml;schung des Nutzerkontos.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">5.3 Der Nutzer stellt </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> von allen Anspr&uuml;chen frei, die von Dritten gegen </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> aufgrund einer Verletzung ihrer Rechte geltend gemacht werden, soweit der Nutzer diese Rechtsverletzung zu vertreten hat. Die Freistellung umfasst die &Uuml;bernahme s&auml;mtlicher Gerichtskosten und angemessener Anwaltskosten.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">5.4 Der Nutzer wird </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> bei der Verteidigung gegen die Inanspruchnahme unterst&uuml;tzen und insbesondere unverz&uuml;glich alle Informationen zur Verf&uuml;gung stellen, die f&uuml;r die Pr&uuml;fung und Abwehr der Anspr&uuml;che von Bedeutung sein k&ouml;nnen.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">5.5 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> ist im Fall der berechtigten Geltendmachung von Rechten durch einen Dritten berechtigt, dem Dritten den Namen und die E-Mail-Adresse des Nutzers mitzuteilen.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">5.6 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> ist zur Geltendmachung weiterer gesetzlicher Rechte im Fall von unzul&auml;ssigen Nutzungshandlungen berechtigt.</span></span></span></p>
    &nbsp;

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>6. Haftungsbeschr&auml;nkung</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">6.1 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> &uuml;bernimmt keine Garantie oder Gew&auml;hr f&uuml;r die Verf&uuml;gbarkeit und Funktion des Online-Tools oder der eingestellten Inhalte. </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> beh&auml;lt sich vor das </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span>&gt;<span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">-Reisewunschportal (auch ohne vorherige Ank&uuml;ndigung) ganz oder teilweise&nbsp;</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">einzustellen oder den Zugang hierzu ganz oder teilweise einzuschr&auml;nken, ohne dass hieraus Anspr&uuml;che der Nutzer gegen&uuml;ber </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> entstehen.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">6.2 F&uuml;r eine Haftung von </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> auf Schadenersatz gelten unbeschadet der sonstigen gesetzlichen Anspruchsvoraussetzungen folgende Haftungsausschl&uuml;sse und Haftungsbegrenzungen</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">6.2.1 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> haftet unbeschr&auml;nkt, soweit die Schadensursache auf Vorsatz oder grober Fahrl&auml;ssigkeit beruht. Ferner haftet </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> f&uuml;r die fahrl&auml;ssige Verletzung von wesentlichen Pflichten, deren Verletzung die Erreichung des Vertragszwecks gef&auml;hrdet, und f&uuml;r die Verletzung von Pflichten auf deren Einhaltung Vertragspartner regelm&auml;&szlig;ig vertrauen. In diesem Fall haftet </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> jedoch nur f&uuml;r den vorhersehbaren, vertragstypischen Schaden. </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> haftet nicht f&uuml;r die fahrl&auml;ssige Verletzung anderer als der in den vorstehenden S&auml;tzen genannten Pflichten. Die vorstehenden Haftungsbeschr&auml;nkungen gelten nicht bei Verletzung von leben, K&ouml;rper und Gesundheit. Im &Uuml;brigen ist die Haftung von </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> ausgeschlossen.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">6.2.2 Soweit die Haftung von </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> ausgeschlossen oder beschr&auml;nkt ist, gilt dies auch f&uuml;r die pers&ouml;nliche Haftung ihrer Arbeitnehmer, Vertreter und Erf&uuml;llungsgehilfen.</span></span></span></p>

    <p><br />
    <span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>7. Datenschutz</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">7.1 Die im Rahmen der Nutzung des Reisewunschportals angegebenen personenbezogenen Daten (Name, E-Mail Adresse) werden zur Bearbeitung des Reisewunsches, zur Kundenbetreuung und Marktforschung oder zur Erf&uuml;llung gesetzlicher Bestimmungen gespeichert, verarbeitet und genutzt. Dar&uuml;ber hinaus k&ouml;nnen die Daten zur Zusendung von aktuellen Informationen und Angeboten verwendet werden. Sollten Sie diese Informationen nicht w&uuml;nschen, wenden Sie sich bitte mit Ihrem Anliegen an: </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">xy@xy.de.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">7.2 Weitere Informationen zur Datenverarbeitung und zum Datenschutz ergeben sich aus unserer Datenschutzerkl&auml;rung. Diese finden Sie hier: </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">https://www.abc.de/datenschutz.</span></span></span></p>
    &nbsp;

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"><strong>8. Schlussbestimmungen</strong></span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">8.1 </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> ist berechtigt, &Auml;nderungen oder Erg&auml;nzungen an diesen Nutzungsbedingungen vorzunehmen, sofern dies dem billigem Ermessen von </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">&nbsp;</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">entspricht und f&uuml;r den Nutzer zumutbar ist. Diese werden erst wirksam, nachdem </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000"> den registrierten Nutzer die &Auml;nderung der Nutzungsbedingungen in Textform mitgeteilt hat und der Nutzer dieser Neufassung nicht innerhalb von 6 Wochen ab Zugang mindestens in Textform widerspricht. Der Nutzer wird bei Mitteilung der &Auml;nderung auf die Bedeutung seines Schweigens besonders hingewiesen.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">8.2 Sofern einzelne oder mehrere Bestimmungen in diesen Nutzungsbedingungen ganz oder teilweise unwirksam oder ung&uuml;ltig sind oder werden, bleibt die Wirksamkeit der &uuml;brigen Regelungen und Bestimmungen hiervon unber&uuml;hrt. Die unwirksame oder ung&uuml;ltige Regelung gilt durch eine Regelung ersetzt, die dem Sinn und Zweck der unwirksamen oder ung&uuml;ltigen Regelung in rechtswirksamer Weise wirtschaftlich am n&auml;chsten kommt. Gleiches gilt f&uuml;r eventuelle Regelungsl&uuml;cken.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">8.3 Streitigkeiten, die im Zusammenhang mit diesen Nutzungsbedingungen oder aufgrund der Nutzung des </span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">$KUNDE</span></span></span><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">-Reisewunschportal gef&uuml;hrt werden unterliegen ausschlie&szlig;lich dem Recht der Bundesrepublik Deutschland.</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">&nbsp;</span></span></span></p>

    <p><span style="font-size:11pt"><span style="font-family:Arial"><span style="color:#000000">Stand: Dezember 2019</span></span></span></p>',

    'stored'            => 'You have successfully stored the Terms and Conditions',
    'not_stored'        => 'Error saving Terms and Conditions',
];
